// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcaufigstulowqtdsbrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYXVmaWdzdHVsb3dxdGRzYnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTc1MzksImV4cCI6MjA2Mjk3MzUzOX0.61YtAoSGQjfYeoOo-8hcluMIzKvqZfz3D9ass2tnr5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);